### ISSUE TITLE
Cloud-init `chpasswd#users` not supported (upstream API deprecation of `chpasswd#list`)

### ISSUE THREAD

**Issue by dzintars** [dmacvicar/terraform-provider-libvirt#980]
### Linux distribution

``` Fedora 35 ```

### Terraform version

```sh
Terraform v1.3.1
on linux_amd6
```

### Provider and libvirt versions

```sh
0.7.0
```

## Cloud-init `chpasswd#users` not supported

`libvirt_cloudinit_disk` resource.

It looks like `list` is deprecated in favor to `users` https://cloudinit.readthedocs.io/en/latest/topics/modules.html#set-passwords

### Setup

This config still works without issues:
```yaml
#cloud-config

users:
  - name: ansible
    groups: users, wheel
    shell: /bin/bash
chpasswd:
  expire: false
  list: |
    ansible:test
```

This config does not work:
```yaml
#cloud-config

users:
  - name: ansible
    groups: users, wheel
    shell: /bin/bash
chpasswd:
  expire: false
  users:
    - name: ansible
      password: test
      type: text
```
